import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BOARD)
GPIO.setup(7,GPIO.OUT)
GPIO.setup(11,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)

GPIO.output(7,GPIO.LOW)
GPIO.output(11,GPIO.LOW)
GPIO.output(13,GPIO.LOW)

for x in range(0,7):
  GPIO.output(7,GPIO.HIGH)
  GPIO.output(11,GPIO.LOW)
  GPIO.output(13,GPIO.LOW)
  time.sleep(1)
  GPIO.output(7,GPIO.HIGH)
  GPIO.output(11,GPIO.HIGH)
  GPIO.output(13,GPIO.LOW)
  time.sleep(1)
  GPIO.output(7,GPIO.HIGH)
  GPIO.output(11,GPIO.HIGH)
  GPIO.output(13,GPIO.HIGH)
  time.sleep(1)
  GPIO.output(7,GPIO.HIGH)
  GPIO.output(11,GPIO.HIGH)
  GPIO.output(13,GPIO.LOW)
  time.sleep(1)
  GPIO.output(7,GPIO.HIGH)
  GPIO.output(11,GPIO.LOW)
  GPIO.output(13,GPIO.LOW)
  time.sleep(1)
  GPIO.output(7,GPIO.LOW)
  GPIO.output(11,GPIO.LOW)
  GPIO.output(13,GPIO.LOW)
GPIO.cleanup()
